name:                hledger-dashboard
version:             0.0.1
github:              "yutotakano/hledger-dashboard"
license:             MIT
author:              "Yuto Takano"
maintainer:          "moa17stock@gmail.com"
copyright:           "2021 Yuto Takano"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yutotakano/hledger-dashboard#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hledger-dashboard-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hledger-dashboard

tests:
  hledger-dashboard-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hledger-dashboard
